### ISSUE TITLE
Accounting tab doesn't show up after a new cluster is created

### ISSUE THREAD

**Issue by jxuamazon** [aws-samples/pcluster-manager#103] opened 2022-04-07 15:08 UTC
After creating a new cluster with accounting feature, the cluster detail doesn't contain the "Accounting" tab.  has to select another cluster, and then back on the new cluster, then the "Accounting" tab shows up.

**Comment by charlesg3** [comment] 2022-04-09 01:25
I think this is a duplicate of #91

**Closed** 2022-04-11 18:44 UTC
Labels: bug, duplicate
